import { Platform, StyleSheet } from "react-native";

import { colors } from "./colors";

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: colors.paper,
  },
  webStage: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    padding: Platform.OS === "web" ? 24 : 0,
    backgroundColor: colors.paper,
  },
  deviceFrame: {
    flex: 1,
    width: "100%",
    maxWidth: Platform.OS === "web" ? 430 : undefined,
    maxHeight: Platform.OS === "web" ? 900 : undefined,
    overflow: "hidden",
    borderWidth: Platform.OS === "web" ? 10 : 0,
    borderColor: "#11191f",
    borderRadius: Platform.OS === "web" ? 38 : 0,
    backgroundColor: "#f8faf9",
    boxShadow: Platform.OS === "web" ? "0 28px 70px rgba(23,32,39,0.2)" : undefined,
  },
  statusLine: {
    height: 42,
    paddingHorizontal: 22,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  statusTime: {
    color: colors.ink,
    fontSize: 13,
    fontWeight: "800",
  },
  statusIcons: {
    flexDirection: "row",
    gap: 4,
  },
  signalDot: {
    width: 5,
    height: 5,
    borderRadius: 3,
    backgroundColor: colors.ink,
  },
  appBrandBar: {
    paddingHorizontal: 18,
    paddingBottom: 4,
  },
  brandMark: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  brandText: {
    color: colors.ink,
    fontSize: 16,
    fontWeight: "800",
  },
  screenSlot: {
    flex: 1,
  },
  animatedScreen: {
    overflow: "hidden",
  },
  screenContent: {
    padding: 18,
    paddingBottom: 26,
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 24,
  },
  compactHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 24,
  },
  compactHeaderTitle: {
    color: colors.ink,
    fontSize: 18,
    fontWeight: "800",
  },
  headerSpacer: {
    width: 42,
    height: 42,
  },
  headerStatusPill: {
    minHeight: 36,
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: 11,
    borderWidth: 1,
    borderColor: "rgba(15,139,141,0.2)",
    borderRadius: 8,
    backgroundColor: colors.white,
  },
  headerStatusText: {
    color: colors.ink,
    fontSize: 12,
    fontWeight: "800",
  },
  kicker: {
    color: colors.teal,
    fontSize: 12,
    fontWeight: "800",
  },
  title: {
    marginTop: 2,
    color: colors.ink,
    fontSize: 24,
    fontWeight: "800",
  },
  iconButton: {
    width: 42,
    height: 42,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: colors.line,
    borderRadius: 8,
    backgroundColor: colors.white,
  },
  iconButtonSoft: {
    backgroundColor: colors.tealSoft,
  },
  pressed: {
    opacity: 0.72,
    transform: [{ scale: 0.98 }],
  },
  primaryButton: {
    minHeight: 46,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    paddingHorizontal: 18,
    borderRadius: 8,
    backgroundColor: colors.teal,
  },
  primaryButtonText: {
    color: colors.white,
    fontSize: 16,
    fontWeight: "800",
  },
  whiteButton: {
    backgroundColor: colors.white,
  },
  whiteButtonText: {
    color: colors.ink,
  },
  dealHero: {
    padding: 22,
    borderRadius: 8,
    backgroundColor: colors.teal,
  },
  dealRoute: {
    color: colors.white,
    fontSize: 14,
    fontWeight: "800",
  },
  dealPrice: {
    marginTop: 12,
    paddingBottom: 3,
    color: colors.white,
    fontSize: 40,
    lineHeight: 46,
    fontWeight: "800",
  },
  dealNote: {
    marginBottom: 24,
    color: "rgba(255,255,255,0.82)",
    fontSize: 14,
    fontWeight: "700",
  },
  chartCard: {
    height: 122,
    marginTop: 18,
    padding: 18,
    flexDirection: "row",
    alignItems: "flex-end",
    gap: 9,
    borderWidth: 1,
    borderColor: colors.line,
    borderRadius: 8,
    backgroundColor: colors.white,
  },
  chartBar: {
    flex: 1,
    minHeight: 18,
    borderTopLeftRadius: 8,
    borderTopRightRadius: 8,
    backgroundColor: colors.amber,
  },
  chartBarLow: {
    backgroundColor: colors.coral,
  },
  listBlock: {
    gap: 10,
    marginTop: 18,
    marginBottom: 18,
  },
  compactDeal: {
    minHeight: 74,
    padding: 14,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    borderWidth: 1,
    borderColor: colors.line,
    borderRadius: 8,
    backgroundColor: colors.white,
  },
  airportCode: {
    color: colors.ink,
    fontSize: 17,
    fontWeight: "800",
  },
  compactRoute: {
    marginTop: 3,
    color: colors.muted,
    fontSize: 13,
    fontWeight: "700",
  },
  compactPrice: {
    color: colors.teal,
    fontSize: 16,
    fontWeight: "800",
  },
  formCard: {
    gap: 10,
  },
  routeSelectCard: {
    gap: 10,
    padding: 12,
    borderWidth: 1,
    borderColor: colors.line,
    borderRadius: 8,
    backgroundColor: colors.white,
  },
  airportSelectField: {
    minHeight: 88,
    padding: 14,
    borderWidth: 1,
    borderColor: colors.line,
    borderRadius: 8,
    backgroundColor: "#fbfcfc",
  },
  airportFieldHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  airportName: {
    marginTop: 8,
    color: colors.ink,
    fontSize: 18,
    lineHeight: 23,
    fontWeight: "800",
  },
  airportMeta: {
    marginTop: 4,
    color: colors.muted,
    fontSize: 12,
    fontWeight: "700",
  },
  swapAirportButton: {
    alignSelf: "center",
    width: 40,
    height: 40,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "rgba(15,139,141,0.25)",
    borderRadius: 8,
    backgroundColor: colors.tealSoft,
  },
  airportPicker: {
    padding: 12,
    borderWidth: 1,
    borderColor: "rgba(15,139,141,0.24)",
    borderRadius: 8,
    backgroundColor: "#f7fcfb",
  },
  airportPickerHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 10,
  },
  airportPickerTitle: {
    color: colors.ink,
    fontSize: 15,
    fontWeight: "800",
  },
  airportCloseButton: {
    width: 30,
    height: 30,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: colors.line,
    borderRadius: 8,
    backgroundColor: colors.white,
  },
  airportList: {
    gap: 7,
  },
  airportOption: {
    minHeight: 56,
    padding: 9,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    borderWidth: 1,
    borderColor: colors.line,
    borderRadius: 8,
    backgroundColor: colors.white,
  },
  airportOptionActive: {
    borderColor: colors.teal,
    backgroundColor: colors.tealSoft,
  },
  airportCodeBadge: {
    width: 46,
    height: 36,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 8,
    backgroundColor: colors.white,
  },
  airportCodeBadgeText: {
    color: colors.teal,
    fontSize: 14,
    fontWeight: "800",
  },
  airportOptionCopy: {
    flex: 1,
  },
  airportOptionName: {
    color: colors.ink,
    fontSize: 13,
    fontWeight: "800",
  },
  airportOptionMeta: {
    marginTop: 3,
    color: colors.muted,
    fontSize: 11,
    fontWeight: "700",
  },
  tripTypeCard: {
    padding: 12,
    borderWidth: 1,
    borderColor: colors.line,
    borderRadius: 8,
    backgroundColor: colors.white,
  },
  field: {
    minHeight: 76,
    padding: 14,
    borderWidth: 1,
    borderColor: colors.line,
    borderRadius: 8,
    backgroundColor: colors.white,
  },
  fieldActive: {
    borderColor: "rgba(15,139,141,0.42)",
    backgroundColor: "#fbfefd",
  },
  fieldHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  fieldLabel: {
    color: colors.muted,
    fontSize: 12,
    fontWeight: "800",
  },
  fieldValue: {
    marginTop: 8,
    color: colors.ink,
    fontSize: 18,
    fontWeight: "800",
  },
  helpButton: {
    width: 26,
    height: 26,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: colors.line,
    borderRadius: 13,
    backgroundColor: colors.white,
  },
  helpButtonActive: {
    borderColor: colors.teal,
    backgroundColor: colors.teal,
  },
  helpButtonText: {
    color: colors.muted,
    fontSize: 14,
    fontWeight: "800",
  },
  helpButtonTextActive: {
    color: colors.white,
  },
  insightCard: {
    marginTop: 12,
    padding: 14,
    borderWidth: 1,
    borderColor: "rgba(15,139,141,0.22)",
    borderRadius: 8,
    backgroundColor: "#f7fcfb",
  },
  insightHeader: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 12,
  },
  insightEyebrow: {
    color: colors.teal,
    fontSize: 11,
    fontWeight: "800",
  },
  insightTitle: {
    marginTop: 3,
    color: colors.ink,
    fontSize: 15,
    fontWeight: "800",
  },
  insightBadge: {
    minHeight: 28,
    justifyContent: "center",
    paddingHorizontal: 10,
    borderRadius: 8,
    backgroundColor: colors.amberSoft,
  },
  insightBadgeText: {
    color: "#7d571a",
    fontSize: 11,
    fontWeight: "800",
  },
  selectedPriceRow: {
    marginTop: 14,
    padding: 12,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    borderRadius: 8,
    backgroundColor: colors.white,
  },
  selectedDate: {
    color: colors.ink,
    fontSize: 14,
    fontWeight: "800",
  },
  selectedCaption: {
    marginTop: 3,
    color: colors.muted,
    fontSize: 11,
    fontWeight: "700",
  },
  selectedPrice: {
    color: colors.coral,
    fontSize: 20,
    fontWeight: "800",
  },
  chartFrame: {
    height: 152,
    marginTop: 12,
    paddingVertical: 5,
    borderWidth: 1,
    borderColor: colors.line,
    borderRadius: 8,
    backgroundColor: colors.white,
  },
  chartLabels: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 6,
    marginTop: 10,
  },
  datePill: {
    minHeight: 28,
    minWidth: 40,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 8,
    borderWidth: 1,
    borderColor: colors.line,
    borderRadius: 8,
    backgroundColor: colors.white,
  },
  datePillActive: {
    borderColor: colors.coral,
    backgroundColor: colors.coralSoft,
  },
  datePillText: {
    color: colors.muted,
    fontSize: 11,
    fontWeight: "800",
  },
  datePillTextActive: {
    color: colors.coral,
  },
  insightStats: {
    flexDirection: "row",
    gap: 8,
    marginTop: 12,
  },
  statBox: {
    flex: 1,
    minHeight: 54,
    padding: 10,
    borderRadius: 8,
    backgroundColor: colors.white,
  },
  statLabel: {
    color: colors.muted,
    fontSize: 10,
    fontWeight: "800",
  },
  statValue: {
    marginTop: 5,
    color: colors.ink,
    fontSize: 13,
    fontWeight: "800",
  },
  targetStat: {
    color: colors.teal,
  },
  preferenceCard: {
    marginTop: 12,
    padding: 14,
    borderWidth: 1,
    borderColor: colors.line,
    borderRadius: 8,
    backgroundColor: colors.white,
  },
  preferenceHeader: {
    marginBottom: 14,
  },
  preferenceTitleRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  preferenceTitle: {
    color: colors.ink,
    fontSize: 16,
    fontWeight: "800",
  },
  preferenceSubtitle: {
    marginTop: 5,
    color: colors.muted,
    fontSize: 12,
    lineHeight: 18,
    fontWeight: "700",
  },
  preferenceLabel: {
    color: colors.muted,
    fontSize: 12,
    fontWeight: "800",
  },
  segmentRow: {
    flexDirection: "row",
    gap: 8,
    marginTop: 9,
  },
  segmentButton: {
    flex: 1,
    minHeight: 42,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: colors.line,
    borderRadius: 8,
    backgroundColor: "#f9fbfa",
  },
  segmentButtonActive: {
    borderColor: "rgba(15,139,141,0.45)",
    backgroundColor: colors.tealSoft,
  },
  segmentText: {
    color: colors.muted,
    fontSize: 14,
    fontWeight: "800",
  },
  segmentTextActive: {
    color: colors.teal,
  },
  directNote: {
    marginTop: 12,
    padding: 12,
    borderRadius: 8,
    backgroundColor: colors.greenSoft,
  },
  directNoteTitle: {
    color: "#27643b",
    fontSize: 14,
    fontWeight: "800",
  },
  directNoteBody: {
    marginTop: 4,
    color: colors.muted,
    fontSize: 12,
    lineHeight: 18,
    fontWeight: "700",
  },
  layoverList: {
    gap: 10,
    marginTop: 12,
  },
  layoverCard: {
    padding: 12,
    borderWidth: 1,
    borderColor: colors.line,
    borderRadius: 8,
    backgroundColor: "#fbfcfc",
  },
  layoverHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
    marginBottom: 10,
  },
  layoverTitle: {
    color: colors.ink,
    fontSize: 14,
    fontWeight: "800",
  },
  layoverSummary: {
    color: colors.teal,
    fontSize: 12,
    fontWeight: "800",
  },
  optionGroup: {
    marginTop: 8,
  },
  optionLabel: {
    marginBottom: 7,
    color: colors.muted,
    fontSize: 11,
    fontWeight: "800",
  },
  chipRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 7,
  },
  choiceChip: {
    minHeight: 32,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 11,
    borderWidth: 1,
    borderColor: colors.line,
    borderRadius: 8,
    backgroundColor: colors.white,
  },
  choiceChipActive: {
    borderColor: colors.teal,
    backgroundColor: colors.tealSoft,
  },
  choiceChipText: {
    color: colors.muted,
    fontSize: 12,
    fontWeight: "800",
  },
  choiceChipTextActive: {
    color: colors.teal,
  },
  baggageSection: {
    gap: 10,
    marginTop: 16,
    paddingTop: 14,
    borderTopWidth: 1,
    borderTopColor: colors.line,
  },
  bagCounter: {
    minHeight: 72,
    padding: 12,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
    borderWidth: 1,
    borderColor: colors.line,
    borderRadius: 8,
    backgroundColor: "#fbfcfc",
  },
  bagCopy: {
    flex: 1,
  },
  bagLabel: {
    color: colors.ink,
    fontSize: 14,
    fontWeight: "800",
  },
  bagCaption: {
    marginTop: 4,
    color: colors.muted,
    fontSize: 12,
    fontWeight: "700",
  },
  stepper: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  stepperButton: {
    width: 34,
    height: 34,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 8,
    backgroundColor: colors.teal,
  },
  stepperButtonDisabled: {
    backgroundColor: "#edf1f1",
  },
  stepperText: {
    color: colors.white,
    fontSize: 20,
    lineHeight: 22,
    fontWeight: "800",
  },
  stepperTextDisabled: {
    color: "#a7b0b6",
  },
  stepperValue: {
    minWidth: 18,
    color: colors.ink,
    textAlign: "center",
    fontSize: 18,
    fontWeight: "800",
  },
  filterRow: {
    marginTop: 18,
    marginBottom: 18,
    flexDirection: "row",
    gap: 8,
  },
  filterButton: {
    flex: 1,
    minHeight: 44,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    borderWidth: 1,
    borderColor: colors.line,
    borderRadius: 8,
    backgroundColor: colors.white,
  },
  filterSelected: {
    borderColor: "rgba(74,159,102,0.45)",
    backgroundColor: colors.greenSoft,
  },
  filterText: {
    color: colors.muted,
    fontWeight: "800",
  },
  filterTextSelected: {
    color: colors.green,
  },
  previewCard: {
    marginBottom: 18,
    padding: 16,
    borderRadius: 8,
    backgroundColor: colors.tealSoft,
  },
  previewTitle: {
    color: colors.ink,
    fontSize: 16,
    fontWeight: "800",
  },
  previewBody: {
    marginTop: 8,
    color: colors.muted,
    fontSize: 14,
    lineHeight: 21,
    fontWeight: "700",
  },
  validationBox: {
    marginTop: 12,
    padding: 12,
    borderWidth: 1,
    borderColor: "rgba(228,111,92,0.34)",
    borderRadius: 8,
    backgroundColor: colors.coralSoft,
  },
  validationText: {
    color: colors.coral,
    fontSize: 13,
    lineHeight: 19,
    fontWeight: "800",
  },
  ticketCard: {
    padding: 20,
    borderRadius: 8,
    backgroundColor: colors.white,
    boxShadow: Platform.OS === "web" ? "0 16px 36px rgba(23,32,39,0.08)" : undefined,
  },
  airportPair: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  bigAirport: {
    width: 76,
    height: 54,
    borderRadius: 8,
    textAlign: "center",
    textAlignVertical: "center",
    color: colors.ink,
    fontSize: 22,
    lineHeight: 54,
    fontWeight: "800",
  },
  bigAirportFrom: {
    backgroundColor: colors.tealSoft,
  },
  bigAirportTo: {
    backgroundColor: colors.coralSoft,
  },
  routeLine: {
    flex: 1,
    height: 2,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.line,
  },
  ticketLabel: {
    marginTop: 28,
    color: colors.muted,
    fontSize: 12,
    fontWeight: "800",
  },
  ticketPrice: {
    marginTop: 8,
    paddingBottom: 3,
    color: colors.ink,
    fontSize: 34,
    lineHeight: 40,
    fontWeight: "800",
  },
  detailGrid: {
    marginTop: 16,
    gap: 10,
    flexDirection: "row",
    flexWrap: "wrap",
  },
  infoCard: {
    width: "48%",
    minHeight: 82,
    padding: 14,
    borderWidth: 1,
    borderColor: colors.line,
    borderRadius: 8,
    backgroundColor: colors.white,
  },
  infoValue: {
    marginTop: 10,
    color: colors.ink,
    fontSize: 16,
    fontWeight: "800",
  },
  timelineCard: {
    gap: 12,
    marginTop: 16,
    marginBottom: 18,
    padding: 16,
    borderWidth: 1,
    borderColor: colors.line,
    borderRadius: 8,
    backgroundColor: colors.white,
  },
  timelineRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  timelineDot: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: colors.coral,
  },
  timelineDotMuted: {
    backgroundColor: colors.teal,
  },
  timelineText: {
    flex: 1,
    color: colors.muted,
    fontSize: 13,
    fontWeight: "700",
  },
  notificationList: {
    gap: 10,
    marginBottom: 18,
  },
  notificationItem: {
    minHeight: 86,
    padding: 14,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    borderWidth: 1,
    borderColor: colors.line,
    borderRadius: 8,
    backgroundColor: colors.white,
  },
  notificationFresh: {
    borderColor: "rgba(228,111,92,0.44)",
    backgroundColor: "#fff8f5",
  },
  notificationIcon: {
    width: 38,
    height: 38,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 8,
    backgroundColor: colors.tealSoft,
  },
  notificationIconFresh: {
    backgroundColor: colors.coralSoft,
  },
  notificationCopy: {
    flex: 1,
  },
  notificationTitle: {
    color: colors.ink,
    fontSize: 15,
    fontWeight: "800",
  },
  notificationSubtitle: {
    marginTop: 4,
    color: colors.muted,
    fontSize: 13,
    fontWeight: "700",
  },
  notificationSummaryCard: {
    padding: 16,
    borderWidth: 1,
    borderColor: "rgba(15,139,141,0.18)",
    borderRadius: 8,
    backgroundColor: colors.tealSoft,
  },
  notificationSummaryTitle: {
    color: colors.ink,
    fontSize: 15,
    fontWeight: "800",
  },
  notificationSummaryBody: {
    marginTop: 7,
    color: colors.muted,
    fontSize: 13,
    lineHeight: 20,
    fontWeight: "700",
  },
  bottomNav: {
    height: 72,
    paddingHorizontal: 14,
    paddingTop: 8,
    flexDirection: "row",
    gap: 8,
    borderTopWidth: 1,
    borderColor: colors.line,
    backgroundColor: colors.white,
  },
  navItem: {
    flex: 1,
    height: 48,
    alignItems: "center",
    justifyContent: "center",
    gap: 4,
    borderRadius: 8,
  },
  navItemActive: {
    backgroundColor: colors.tealSoft,
  },
  navText: {
    color: colors.muted,
    fontSize: 11,
    fontWeight: "800",
  },
  navTextActive: {
    color: colors.teal,
  },
});
